queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label=S:automerge
    merge_conditions:
      - base=master
      - label=S:automerge
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: backport patches to v0.34.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.34.x
    actions:
      backport:
        branches:
          - v0.34.x
  - name: backport patches to v0.35.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.35.x
    actions:
      backport:
        branches:
          - v0.35.x
  - name: backport patches to v0.36.x branch
    conditions:
      - base=master
      - label=S:backport-to-v0.36.x
    actions:
      backport:
        branches:
          - v0.36.x
  - name: Automerge to master
    conditions: []
    actions:
      queue:
